USE WAREHOUSE WH_WHOOP_ANALYTICS;
USE DATABASE WHOOP_PORTFOLIO;
USE SCHEMA ANALYTICS;

-- 1) Ticket details per member
CREATE OR REPLACE VIEW V_TICKETS_ENRICHED AS
SELECT
  t.*,
  m.MEMBERSHIP_PLAN,
  m.DEVICE_VERSION,
  m.PRIMARY_GOAL,
  m.COUNTRY,
  m.TENURE_DAYS,
  m.CHURN_FLAG,
  m.CHURN_DATE
FROM WHOOP_PORTFOLIO.RAW.TICKETS t
JOIN WHOOP_PORTFOLIO.RAW.MEMBERS m
  ON t.MEMBER_ID = m.MEMBER_ID;

-- 2) Member-level analytics view
CREATE OR REPLACE VIEW V_MEMBER_ANALYTICS AS
SELECT
  m.MEMBER_ID,
  m.SIGNUP_DATE,
  m.MEMBERSHIP_PLAN,
  m.DEVICE_VERSION,
  m.PRIMARY_GOAL,
  m.COUNTRY,
  m.TENURE_DAYS,
  COALESCE(s.TOTAL_TICKETS, 0) AS TOTAL_TICKETS,
  COALESCE(s.AVG_CSAT, 4.6) AS AVG_CSAT,
  COALESCE(s.TOTAL_REPEAT_CONTACTS, 0) AS TOTAL_REPEAT_CONTACTS,
  COALESCE(s.TOTAL_ESCALATIONS, 0) AS TOTAL_ESCALATIONS,
  COALESCE(s.AVG_RESOLUTION_TIME, 12.0) AS AVG_RESOLUTION_TIME,
  m.CHURN_FLAG,
  m.CHURN_DATE
FROM WHOOP_PORTFOLIO.RAW.MEMBERS m
LEFT JOIN WHOOP_PORTFOLIO.RAW.MEMBER_SUPPORT_SUMMARY s
  ON m.MEMBER_ID = s.MEMBER_ID;