USE WAREHOUSE WH_WHOOP_ANALYTICS;
USE DATABASE WHOOP_PORTFOLIO;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE MEMBERS (
  MEMBER_ID NUMBER,
  SIGNUP_DATE DATE,
  MEMBERSHIP_PLAN STRING,        
  DEVICE_VERSION STRING,          
  PRIMARY_GOAL STRING,            
  COUNTRY STRING,                
  TENURE_DAYS NUMBER,
  TOTAL_TICKETS NUMBER,
  AVG_CSAT FLOAT,
  TOTAL_REPEAT_CONTACTS NUMBER,
  TOTAL_ESCALATIONS NUMBER,
  AVG_RESOLUTION_TIME FLOAT,
  CHURN_FLAG NUMBER,
  CHURN_DATE DATE
);

CREATE OR REPLACE TABLE TICKETS (
  TICKET_ID NUMBER,
  MEMBER_ID NUMBER,
  CONTACT_DATE DATE,
  CHANNEL STRING,                 
  ISSUE_CATEGORY STRING,
  RESOLUTION_TIME_HOURS FLOAT,
  FIRST_CONTACT_RESOLUTION NUMBER,
  ESCALATED NUMBER,
  CSAT_SCORE NUMBER,
  REPEAT_CONTACT_FLAG NUMBER
);

CREATE OR REPLACE TABLE MEMBER_SUPPORT_SUMMARY (
  MEMBER_ID NUMBER,
  TOTAL_TICKETS NUMBER,
  AVG_CSAT FLOAT,
  TOTAL_REPEAT_CONTACTS NUMBER,
  TOTAL_ESCALATIONS NUMBER,
  AVG_RESOLUTION_TIME FLOAT
);