CREATE OR REPLACE WAREHOUSE WH_WHOOP_ANALYTICS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE WHOOP_PORTFOLIO;
CREATE OR REPLACE SCHEMA WHOOP_PORTFOLIO.RAW;
CREATE OR REPLACE SCHEMA WHOOP_PORTFOLIO.ANALYTICS;

USE WAREHOUSE WH_WHOOP_ANALYTICS;
USE DATABASE WHOOP_PORTFOLIO;
USE SCHEMA RAW;